# Generated by Django 2.1.15 on 2020-06-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('creatingdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('A_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BankData.User')),
                ('amount', models.IntegerField()),
                ('creatingdate', models.DateField()),
                ('account', models.CharField(max_length=100)),
            ],
        ),
    ]
